<?php 

function zulumax_modules_extended_feeds_plugins ()
{
	$info = array();
	
	$info ['HTTP Fetcher (Extended version)'] = array
	(
    'name'				=> 'HTTP Fetcher Extended',
    'description'	=> 'Download content from a URL. Enables the POST-type fetches.',
    'handler'			=> array
    (
			'parent'		=> 'FeedsFetcher',
      'class'			=> 'FeedsHTTPExtendedFetcher',
      'file'			=> 'FeedsHTTPExtendedFetcher.inc',
      'path'			=> drupal_get_path ('module', 'zulumax_modules_extended') . '/modules/feeds/'
	),
	);
	return $info;
}

function zulumax_modules_extended_enable ()
{
	cache_clear_all ('plugins:feeds:plugins', 'cache');
}

?>